export const projects: ProjectCardProps[] = [
  {
    id: 1,
    status: "Finalizado",
    title:
      "Projeto Encodar titulo longo muito longo longo logo mesmo aqui é longo para caraio",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but.",
    technologiesTag: [
      "Java",
      "Spring Boot",
      "JPA",
      "Node.js",
      "React",
      "TypeScript",
      "Docker",
      "PostgreSQL",
      "Redis",
      "MongoDB",
      "Kubernetes",
      "AWS",
      "GraphQL",
      "Next.js",
      "Tailwind CSS",
      "Jest",
      "Cypress",
    ],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "desafio técnico",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-02-01"),
  },
  {
    id: 2,
    status: "Em progresso",
    title: "Projeto Encodar",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "acadêmico",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-03-01"),
  },
  {
    id: 3,
    status: "Finalizado",
    title: "Projeto Encodar",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    type: "pessoal",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-04-01"),
  },
  {
    id: 4,
    status: "Finalizado",
    title: "Projeto Encodar",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    type: "pessoal",
    startDate: new Date("2024-04-01"),
    endDate: new Date("2024-05-01"),
  },
  {
    id: 5,
    status: "Finalizado",
    title: "Projeto Encodar",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    type: "pessoal",
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-06-01"),
  },
  {
    id: 6,
    status: "Em progresso",
    title: "Projeto Encodar 6",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-06-01"),
    endDate: new Date("2024-07-01"),
  },
  {
    id: 7,
    status: "Finalizado",
    title: "Projeto Encodar 7",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-07-01"),
    endDate: new Date("2024-08-01"),
  },
  {
    id: 8,
    status: "Em progresso",
    title: "Projeto Encodar 8",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2024-09-01"),
  },
  {
    id: 9,
    status: "Finalizado",
    title: "Projeto Encodar 9",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2024-10-01"),
  },
  {
    id: 10,
    status: "Em progresso",
    title: "Projeto Encodar 10",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-10-01"),
    endDate: new Date("2024-11-01"),
  },
  {
    id: 11,
    status: "Finalizado",
    title: "Projeto Encodar 11",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-11-01"),
    endDate: new Date("2024-12-01"),
  },
  {
    id: 12,
    status: "Em progresso",
    title: "Projeto Encodar 12",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2024-12-01"),
    endDate: new Date("2025-01-01"),
  },
  {
    id: 13,
    status: "Finalizado",
    title: "Projeto Encodar 13",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-01-01"),
    endDate: new Date("2025-02-01"),
  },
  {
    id: 14,
    status: "Em progresso",
    title: "Projeto Encodar 14",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-02-01"),
    endDate: new Date("2025-03-01"),
  },
  {
    id: 15,
    status: "Finalizado",
    title: "Projeto Encodar 15",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-03-01"),
    endDate: new Date("2025-04-01"),
  },
  {
    id: 16,
    status: "Em progresso",
    title: "Projeto Encodar 16",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-04-01"),
    endDate: new Date("2025-05-01"),
  },
  {
    id: 17,
    status: "Finalizado",
    title: "Projeto Encodar 17",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-06-01"),
  },
  {
    id: 18,
    status: "Em progresso",
    title: "Projeto Encodar 18",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-07-01"),
  },
  {
    id: 19,
    status: "Finalizado",
    title: "Projeto Encodar 19",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-08-01"),
  },
  {
    id: 20,
    status: "Em progresso",
    title: "Projeto Encodar 20",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-09-01"),
  },
  {
    id: 21,
    status: "Finalizado",
    title: "Projeto Encodar 21",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-10-01"),
  },
  {
    id: 22,
    status: "Em progresso",
    title: "Projeto Encodar 22",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-11-01"),
  },
  {
    id: 23,
    status: "Finalizado",
    title: "Projeto Encodar 23",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-11-01"),
    endDate: new Date("2025-12-01"),
  },
  {
    id: 24,
    status: "Em progresso",
    title: "Projeto Encodar 24",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2025-12-01"),
    endDate: new Date("2026-01-01"),
  },
  {
    id: 25,
    status: "Finalizado",
    title: "Projeto Encodar 25",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has survived not only five centuries, mas.",
    technologiesTag: ["Java", "Spring Boot", "JPA"],
    repository: "#",
    images: [
      "https://i0.wp.com/blog.portaleducacao.com.br/wp-content/uploads/2022/02/365-O-que-e%CC%81-tecnologia_.jpg",
    ],
    type: "pessoal",
    startDate: new Date("2026-01-01"),
    endDate: new Date("2026-02-01"),
  },
]
